### PR TITLE
Symfony messager and RabbitMQ

### PR DESCRIPTION
**Pull request by cableman**
If this can be approved, changes are still needed in upload and front end.

Also note that message coverting from one type to another is not optimal (but to keep the no. of potential errors down I think this should be refactored in another PR).

**Requires**: https://github.com/danskernesdigitalebibliotek/ddb-cover-service-upload/pull/28 and https://github.com/danskernesdigitalebibliotek/ddb-cover-service/pull/107

### CODE REVIEW

**Review by turegjorup — COMMENTED** [review]
This looks good, but it's a big change. And as you state this requires changes to other `upload` and `frontend`. Even when approved, this PR should NOT be merged until we have a plan for updating and releasing all round.

A number of general notes:
* If we do this, we should do it fully and refactor the events we use to be messages
* I know RabbitMQ is the defacto standard but it is also yet another component we need to run. Currently we have seen issues with both ES and Redis. Using Symfony Messenger allows us to be "message storage agnostic" because we can switch transports just by changing config. I think we should embrace that and look to [Azure Queues](https://docs.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction) to limit our number of dependencies. This will require a transport like https://github.com/alexandrubau/messenger-azure-queue-transport
* We should configure a `failure_transport` to collect failed jobs. I know we have logging, but we know it's not bulletproof. We need to be able to inspect failed messages for debugging (see https://symfony.com/doc/current/messenger.html#retries-failures)
* We should reconsider our queues. The current `search-queue`, `cover-store-queue`, etc reflect our understanding when using Enqueue. I think a better approach would be to have queues by priority and use the routing to control what goes where. We could have `priority_high`, `priority_normal` and `priority_low`, then have consumers consume them all to avoid idle consumers: `php bin/console messenger:consume priority_high priority_normal priority_low` (See: https://symfony.com/doc/current/messenger.html#prioritized-transports)
* I don't know if messages can be versioned to better support sharing messages between services, but we should look further to this

Minor things:
* We should add the the AMQP PHP extension as an dependency in `composer.json` if we use that transport
* Readme still have examples with `enqueue:consume`  

Just my thoughts for now. Let's keep working on this 😄 🚀

**Comment by cableman** [comment]
The other upload/frontend are on the way

* I don't think we should split it into steps and not changes the events in the first step
* I have not configured failed transporter as there would be may of these - on all no-hits currently (made this way as an step one to make as few changes as possible)
* I think we should keep queue names, so we have the possibility to stop process single queue and not mix up the different queues
* Real don't what to use azure queues - as vendor lock-in - and also sending data outside k8s is way slower and I what to keep data inside the cluster

**Comment by turegjorup** [comment]
Readme needs to updated with latest queue changes. It still has references to `cover-store-queue` etc. A brief description on RabbitMQ and the available management interface would nice but is not required.

Unrelated: Also has instructions for `enqueue:consume` in section about TheMovieDatabase. This section can be removed as far as I can tell.

**Review by turegjorup — APPROVED** [review]

**Comment by turegjorup** [comment]
Test failing because we are not compatible with Composer 2. We can lock it to Composer 1 with `tools: composer:v1` (https://github.com/shivammathur/setup-php#wrench-tools-support) or we can try to update dependencies?

**Pull request merged**
